name: SAST

on:
  pull_request:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: sast-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
    runs-on: ubuntu-20.04
    name: CodeQL ( ${{ matrix.language }} )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Initialize
        uses: github/codeql-action/init@16964e90ba004cdf0cd845b866b5df21038b7723
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@16964e90ba004cdf0cd845b866b5df21038b7723
      - name: Analize
        uses: github/codeql-action/analyze@16964e90ba004cdf0cd845b866b5df21038b7723
