name: Tester

on:
  pull_request:
    branches:
      - main
      - releases/**

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-20.04
    outputs:
      app-source: ${{ steps.filter.outputs.app-source }}
    name: Changes
    steps:
      - name: Filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app-source:
              - '.storybook/**'
              - 'public/**'
              - 'src/**'
              - 'tests/**'
              - '.eslintignore'
              - '.eslintrc.js'
              - 'babel.config.js'
              - 'jest.config.js'
              - 'package-lock.json'
              - 'package.json'
              - 'vue.config.json'

  testing:
    needs: changes
    if: ${{ needs.changes.outputs.app-source == 'true' }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    name: Testing on Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Add required npm registry
        run: npm config set '@bit:registry' https://node.bit.dev
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Check Lint
        run: npm run lint:check
      - name: Run Unit Test
        run: npm run test:unit
      - name: Run Build
        run: npm run build
